import type { NavigationItem } from "../types/App.type";

export const NAVIGATION_ITEMS: NavigationItem[] = [
	{ id: "docker", label: "Docker" },
	{ id: "workspace", label: "Workspace Launcher" },
	{ id: "ansible", label: "Ansible" },
	{ id: "writer", label: "Bilingual Writer" },
	{ id: "jenkins", label: "Jenkins" },
	{ id: "formatter", label: "Smart Formatter" },
	{ id: "diff", label: "Compare Files" },
	{ id: "excel", label: "JSON / CSV / Excel" },
	{ id: "cheatsheet", label: "Quick Start / CLI" },
	{ id: "vault", label: "Secure Vault" },
	{ id: "notebook", label: "Notebook" },
	{ id: "fakeDataGenerator", label: "Fake Data Generator" },
	{ id: "timeConverter", label: "Time Converter" },
	{ id: "commands", label: "Encoding Tools" },
	{ id: "apiClient", label: "API Client" },
	{ id: "websocketSse", label: "WebSocket / SSE" },
	{ id: "jwtInspector", label: "JWT Inspector" },
	{ id: "kubernetes", label: "Kubernetes" },
	{ id: "networkToolbox", label: "Network Toolbox" },
	{ id: "cronBuilder", label: "Cron Builder" },
	{ id: "tlsChecker", label: "TLS Checker" },
	{ id: "database", label: "Database" },
	{ id: "redis", label: "Redis" },
	{ id: "kafka", label: "Kafka" },
	{ id: "logAnalyzer", label: "Log Analyzer" },
	{ id: "springBootInspector", label: "Spring Boot Inspector" },
	{ id: "portProcessInspector", label: "Port / Process Inspector" },
	{ id: "environmentDiff", label: "Environment Diff" },
	{ id: "secretScanner", label: "Secret Scanner" },
	{ id: "hashGenerator", label: "Hash Generator" },
];
